name: Music Transposition API CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pydantic python-multipart openai python-dotenv pytest pytest-cov httpx
      - name: Create dummy .env file for tests
        run: |
          echo "OPENAI_API_KEY=dummy-key-for-testing" > .env
      - name: Run tests
        run: |
          pytest -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pydantic python-multipart openai python-dotenv
      # Commented out Azure deployment until credentials are set up
      # - name: Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - name: Deploy to Azure App Service
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: 'music-transposition-api'
      #     slot-name: 'production'
      #     publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
      - name: Deployment placeholder
        run: echo "Deployment would happen here once Azure credentials are configured"